// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delivery.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeliveryTimes = `-- name: DeleteDeliveryTimes :exec
delete from deliveryTime where email_id = $1 returning id, delivery_time, date_added, email_id
`

func (q *Queries) DeleteDeliveryTimes(ctx context.Context, emailID string) error {
	_, err := q.db.Exec(ctx, deleteDeliveryTimes, emailID)
	return err
}

const getDeliveryTimes = `-- name: GetDeliveryTimes :many
select id, delivery_time, date_added, email_id from deliveryTime where email_id = $1
`

func (q *Queries) GetDeliveryTimes(ctx context.Context, emailID string) ([]Deliverytime, error) {
	rows, err := q.db.Query(ctx, getDeliveryTimes, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deliverytime{}
	for rows.Next() {
		var i Deliverytime
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryTime,
			&i.DateAdded,
			&i.EmailID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliveryTime = `-- name: SetDeliveryTime :one
insert into deliveryTime (id, delivery_time, email_id)
values ($1, $2, $3)
returning id, delivery_time, date_added, email_id
`

type SetDeliveryTimeParams struct {
	ID           string      `json:"id"`
	DeliveryTime pgtype.Time `json:"delivery_time"`
	EmailID      string      `json:"email_id"`
}

func (q *Queries) SetDeliveryTime(ctx context.Context, arg SetDeliveryTimeParams) (Deliverytime, error) {
	row := q.db.QueryRow(ctx, setDeliveryTime, arg.ID, arg.DeliveryTime, arg.EmailID)
	var i Deliverytime
	err := row.Scan(
		&i.ID,
		&i.DeliveryTime,
		&i.DateAdded,
		&i.EmailID,
	)
	return i, err
}
