// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: email.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activate = `-- name: Activate :exec
update email set running = true where id = $1 and user_id = $2
`

type ActivateParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) Activate(ctx context.Context, arg ActivateParams) error {
	_, err := q.db.Exec(ctx, activate, arg.ID, arg.UserID)
	return err
}

const addEmail = `-- name: AddEmail :one
insert into email (id, email_address, account_name, profile_picture, user_id, primaryAccount, oauth2_token) values ($1, $2, $3, $4, $5, $6, $7) returning id, email_address, account_name, profile_picture, date_added, user_id, primaryaccount, running, oauth2_token, hold_filter_id, block_filter_id
`

type AddEmailParams struct {
	ID             string `json:"id"`
	EmailAddress   string `json:"email_address"`
	AccountName    string `json:"account_name"`
	ProfilePicture string `json:"profile_picture"`
	UserID         string `json:"user_id"`
	Primaryaccount bool   `json:"primaryaccount"`
	Oauth2Token    []byte `json:"oauth2_token"`
}

func (q *Queries) AddEmail(ctx context.Context, arg AddEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, addEmail,
		arg.ID,
		arg.EmailAddress,
		arg.AccountName,
		arg.ProfilePicture,
		arg.UserID,
		arg.Primaryaccount,
		arg.Oauth2Token,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.AccountName,
		&i.ProfilePicture,
		&i.DateAdded,
		&i.UserID,
		&i.Primaryaccount,
		&i.Running,
		&i.Oauth2Token,
		&i.HoldFilterID,
		&i.BlockFilterID,
	)
	return i, err
}

const getAllUserEmails = `-- name: GetAllUserEmails :many
select id, email_address, account_name, profile_picture, date_added, user_id, primaryaccount, running, oauth2_token, hold_filter_id, block_filter_id from email where user_id = $1
`

func (q *Queries) GetAllUserEmails(ctx context.Context, userID string) ([]Email, error) {
	rows, err := q.db.Query(ctx, getAllUserEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Email{}
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.AccountName,
			&i.ProfilePicture,
			&i.DateAdded,
			&i.UserID,
			&i.Primaryaccount,
			&i.Running,
			&i.Oauth2Token,
			&i.HoldFilterID,
			&i.BlockFilterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmail = `-- name: GetEmail :one
select id, email_address, account_name, profile_picture, date_added, user_id, primaryaccount, running, oauth2_token, hold_filter_id, block_filter_id from email where email_address = $1 and user_id = $2 limit 1
`

type GetEmailParams struct {
	EmailAddress string `json:"email_address"`
	UserID       string `json:"user_id"`
}

func (q *Queries) GetEmail(ctx context.Context, arg GetEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmail, arg.EmailAddress, arg.UserID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.AccountName,
		&i.ProfilePicture,
		&i.DateAdded,
		&i.UserID,
		&i.Primaryaccount,
		&i.Running,
		&i.Oauth2Token,
		&i.HoldFilterID,
		&i.BlockFilterID,
	)
	return i, err
}

const getEmailByEmailAddress = `-- name: GetEmailByEmailAddress :one
select id, email_address, account_name, profile_picture, date_added, user_id, primaryaccount, running, oauth2_token, hold_filter_id, block_filter_id from email where email_address = $1 limit 1
`

func (q *Queries) GetEmailByEmailAddress(ctx context.Context, emailAddress string) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByEmailAddress, emailAddress)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.AccountName,
		&i.ProfilePicture,
		&i.DateAdded,
		&i.UserID,
		&i.Primaryaccount,
		&i.Running,
		&i.Oauth2Token,
		&i.HoldFilterID,
		&i.BlockFilterID,
	)
	return i, err
}

const updateHoldFilterID = `-- name: UpdateHoldFilterID :exec
update email set hold_filter_id = $1 where id = $2 and user_id = $3
`

type UpdateHoldFilterIDParams struct {
	HoldFilterID pgtype.Text `json:"hold_filter_id"`
	ID           string      `json:"id"`
	UserID       string      `json:"user_id"`
}

func (q *Queries) UpdateHoldFilterID(ctx context.Context, arg UpdateHoldFilterIDParams) error {
	_, err := q.db.Exec(ctx, updateHoldFilterID, arg.HoldFilterID, arg.ID, arg.UserID)
	return err
}
