// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deliverytime struct {
	ID           string             `json:"id"`
	DeliveryTime string             `json:"delivery_time"`
	DateAdded    pgtype.Timestamptz `json:"date_added"`
	EmailAddress string             `json:"email_address"`
}

type Email struct {
	ID             string             `json:"id"`
	EmailAddress   string             `json:"email_address"`
	AccountName    string             `json:"account_name"`
	ProfilePicture string             `json:"profile_picture"`
	DateAdded      pgtype.Timestamptz `json:"date_added"`
	UserID         string             `json:"user_id"`
	Primaryaccount bool               `json:"primaryaccount"`
	Running        bool               `json:"running"`
	Oauth2Token    []byte             `json:"oauth2_token"`
	HoldFilterID   pgtype.Text        `json:"hold_filter_id"`
	BlockFilterID  pgtype.Text        `json:"block_filter_id"`
}

type User struct {
	ID           string             `json:"id"`
	RegisterDate pgtype.Timestamptz `json:"register_date"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}

type Vipdomain struct {
	ID           string             `json:"id"`
	DomainName   string             `json:"domain_name"`
	DateAdded    pgtype.Timestamptz `json:"date_added"`
	EmailAddress string             `json:"email_address"`
}

type Vipemailaddress struct {
	ID              string             `json:"id"`
	VipEmailAddress string             `json:"vip_email_address"`
	DateAdded       pgtype.Timestamptz `json:"date_added"`
	EmailAddress    string             `json:"email_address"`
}

type Vipkeyword struct {
	ID           string             `json:"id"`
	Keyword      string             `json:"keyword"`
	DateAdded    pgtype.Timestamptz `json:"date_added"`
	EmailAddress string             `json:"email_address"`
}
