// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: vipemails.sql

package sqlc

import (
	"context"
)

const addVipEmail = `-- name: AddVipEmail :one
insert into vipEmailAddress (vip_email_address, email_address)
values ($1, $2)
returning vip_email_address, date_added, email_address
`

type AddVipEmailParams struct {
	VipEmailAddress string `json:"vip_email_address"`
	EmailAddress    string `json:"email_address"`
}

func (q *Queries) AddVipEmail(ctx context.Context, arg AddVipEmailParams) (Vipemailaddress, error) {
	row := q.db.QueryRow(ctx, addVipEmail, arg.VipEmailAddress, arg.EmailAddress)
	var i Vipemailaddress
	err := row.Scan(&i.VipEmailAddress, &i.DateAdded, &i.EmailAddress)
	return i, err
}

const deleteVipEmails = `-- name: DeleteVipEmails :exec
delete from vipEmailAddress where email_address = $1
`

func (q *Queries) DeleteVipEmails(ctx context.Context, emailAddress string) error {
	_, err := q.db.Exec(ctx, deleteVipEmails, emailAddress)
	return err
}

const getVipEmails = `-- name: GetVipEmails :many
select vip_email_address, date_added, email_address from vipEmailAddress where email_address = $1
`

func (q *Queries) GetVipEmails(ctx context.Context, emailAddress string) ([]Vipemailaddress, error) {
	rows, err := q.db.Query(ctx, getVipEmails, emailAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vipemailaddress{}
	for rows.Next() {
		var i Vipemailaddress
		if err := rows.Scan(&i.VipEmailAddress, &i.DateAdded, &i.EmailAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
